"use client"
import {useEffect,useMemo,useState} from "react"
import {Check,Clock3,Coins,Mail,Plus,RefreshCw,Save,Send,Settings2,ShieldCheck,X} from "lucide-react"
import {Card,CardContent,CardHeader,CardTitle,CardDescription} from "@/components/ui/card"
import {Button} from "@/components/ui/button"
import {Input} from "@/components/ui/input"
import {Badge} from "@/components/ui/badge"
import {Textarea} from "@/components/ui/textarea"
import {artApi} from "@/lib/art-api"
import {useAdminAuth} from "@/contexts/admin-auth-context"

export default function MembershipPage(){
 const {hasPermission}=useAdminAuth(); const [tab,setTab]=useState("members");
 const [members,setMembers]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]);
 const [settings,setSettings]=useState<any>({enabled:true,earnPer100:1,coinValue:1,maxRedeemPercent:30,minRedeemCoins:1});
 const [loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(false),[add,setAdd]=useState<any>(null),[message,setMessage]=useState<any>(null),[broadcast,setBroadcast]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const [m,r,p,s,cr]=await Promise.all([artApi.members(),artApi.membershipRequests(),artApi.products(),artApi.coinSettings(),artApi.coinRules()]);setMembers(m);setRequests(r);setProducts(p);setSettings(s);setRules(cr)}catch(e:any){setError(e.message||"Could not load membership data")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const ruleMap=useMemo(()=>Object.fromEntries(rules.map(r=>[r.productId,r])),[rules]);
 const pending=requests.filter(r=>r.status==="pending");
 const saveSettings=async()=>{setSaving(true);try{await artApi.updateCoinSettings({...settings,earnPer100:Number(settings.earnPer100)||0,coinValue:Number(settings.coinValue)||1,maxRedeemPercent:Number(settings.maxRedeemPercent)||30,minRedeemCoins:Number(settings.minRedeemCoins)||1});await load()}catch(e:any){setError(e.message)}finally{setSaving(false)}};
 const addMember=async(e:any)=>{e.preventDefault();setSaving(true);try{await artApi.addMember(add);setAdd(null);await load()}catch(e:any){setError(e.message)}finally{setSaving(false)}};
 const review=async(id:string,status:string)=>{try{await artApi.reviewMembershipRequest(id,status);await load()}catch(e:any){setError(e.message)}};
 const adjust=async(m:any)=>{const raw=window.prompt(`Set reward coins for ${m.name||m.email}`,String(m.coinBalance||0));if(raw===null)return;try{await artApi.updateMember(m.uid,{coinBalance:Math.max(0,Math.floor(Number(raw)||0))});await load()}catch(e:any){setError(e.message)}};
 const saveRule=async(p:any)=>{const current=ruleMap[p.id]||{};try{await artApi.updateCoinRule(p.id,{disabled:current.disabled===true,earnPer100:Math.max(0,Number(current.earnPer100 ?? settings.earnPer100)||0)});await load()}catch(e:any){setError(e.message)}};
 const toggleRule=async(p:any,disabled:boolean)=>{const current=ruleMap[p.id]||{};try{await artApi.updateCoinRule(p.id,{disabled,earnPer100:Math.max(0,Number(current.earnPer100 ?? settings.earnPer100)||0)});await load()}catch(e:any){setError(e.message)}};
 const changeRate=(id:string,v:any)=>setRules(rs=>{const old=ruleMap[id]||{productId:id,disabled:false,earnPer100:settings.earnPer100};const next={...old,earnPer100:v};return [...rs.filter(x=>x.productId!==id),next]});
 const sendBroadcast=async()=>{if(!broadcast.trim())return;setSaving(true);try{const result=await artApi.broadcastMembers(broadcast.trim());setBroadcast("");alert(`Announcement delivered in-app to ${result.sent||0} members and emailed to ${result.emailSent||0}.`)}catch(e:any){setError(e.message)}finally{setSaving(false)}};
 if(!hasPermission("manageMembership"))return <div className="px-4 lg:px-6"><Card><CardHeader><CardTitle>Membership</CardTitle><CardDescription>No permission.</CardDescription></CardHeader></Card></div>;
 return <div className="px-4 lg:px-6 space-y-6 pb-10">
  <div className="flex justify-between gap-4 flex-wrap"><div><p className="text-xs uppercase tracking-[.18em] text-primary">Community / Rewards</p><h1 className="text-3xl font-semibold mt-1">ArtCanvas Membership</h1><p className="text-sm text-muted-foreground mt-2">Free membership, approval, reward coins and member announcements.</p></div><Button variant="outline" onClick={load}><RefreshCw className="size-4 mr-2"/>Refresh</Button></div>
  {error&&<div className="rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}
  <div className="grid sm:grid-cols-3 gap-4"><Card><CardContent className="p-5"><p className="text-xs text-muted-foreground">Active members</p><p className="text-3xl font-semibold mt-2">{members.length}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-xs text-muted-foreground">Pending requests</p><p className="text-3xl font-semibold mt-2">{pending.length}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-xs text-muted-foreground">Coins issued</p><p className="text-3xl font-semibold mt-2">{members.reduce((a,m)=>a+Number(m.coinBalance||0),0).toLocaleString()}</p></CardContent></Card></div>
  <div className="flex flex-wrap gap-2 border-b pb-2">{[["members","Members"],["requests","Requests"],["coins","Coin Rules"],["announce","Announcements"]].map(([id,label])=><Button key={id} variant={tab===id?"default":"ghost"} onClick={()=>setTab(id)}>{label}</Button>)}</div>
  {tab==="members"&&<div className="space-y-4"><div className="flex justify-end"><Button onClick={()=>setAdd({email:"",phone:"",name:"",coinBalance:0})}><Plus className="size-4 mr-2"/>Add member</Button></div>{add&&<Card><CardHeader><CardTitle>Add member directly</CardTitle><CardDescription>The customer must already have an ArtCanvas account.</CardDescription></CardHeader><CardContent><form onSubmit={addMember} className="grid md:grid-cols-3 gap-4"><Input placeholder="Email" value={add.email} onChange={e=>setAdd({...add,email:e.target.value})}/><Input placeholder="Phone" value={add.phone} onChange={e=>setAdd({...add,phone:e.target.value})}/><Input placeholder="Name" value={add.name} onChange={e=>setAdd({...add,name:e.target.value})}/><Input type="number" min="0" placeholder="Starting coins" value={add.coinBalance} onChange={e=>setAdd({...add,coinBalance:e.target.value})}/><div className="md:col-span-2 flex gap-2"><Button disabled={saving}>{saving?"Saving…":"Add member"}</Button><Button type="button" variant="outline" onClick={()=>setAdd(null)}>Cancel</Button></div></form></CardContent></Card>}
   <Card><CardHeader><CardTitle>Active members</CardTitle><CardDescription>Coin balances are visible only to authorized admins.</CardDescription></CardHeader><CardContent>{loading?<p className="text-sm text-muted-foreground">Loading…</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3">Member</th><th>Phone</th><th>Joined</th><th>Coins</th><th className="text-right">Actions</th></tr></thead><tbody>{members.map(m=><tr key={m.uid} className="border-b last:border-0"><td className="py-3"><p className="font-medium">{m.name||"Member"}</p><p className="text-xs text-muted-foreground">{m.email}</p></td><td>{m.phone||"—"}</td><td>{m.joinedAt?new Date(m.joinedAt).toLocaleDateString():"—"}</td><td><Badge variant="secondary">{Number(m.coinBalance||0).toLocaleString()} coins</Badge></td><td className="text-right"><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={()=>adjust(m)}><Coins className="size-4 mr-1"/>Adjust</Button><Button size="sm" variant="outline" onClick={()=>setMessage({uid:m.uid,name:m.name||m.email,text:""})}><Send className="size-4 mr-1"/>Message</Button></div></td></tr>)}</tbody></table></div>}</CardContent></Card>
   {message&&<Card><CardHeader><CardTitle>Message {message.name}</CardTitle><CardDescription>This message will be delivered to the member's email and saved in their ArtCanvas inbox.</CardDescription></CardHeader><CardContent><Textarea placeholder="Write a private member message…" value={message.text} onChange={e=>setMessage({...message,text:e.target.value})}/><div className="flex gap-2 mt-3"><Button disabled={saving||!message.text.trim()} onClick={async()=>{setSaving(true);try{await artApi.messageMember(message.uid,message.text);setMessage(null);alert("Message emailed successfully.")}catch(e:any){setError(e.message)}finally{setSaving(false)}}}>{saving?"Sending…":"Send email"}</Button><Button variant="outline" onClick={()=>setMessage(null)}>Cancel</Button></div></CardContent></Card>}
  </div>}
  {tab==="requests"&&<Card><CardHeader><CardTitle>Membership requests</CardTitle><CardDescription>Customers join for free, then an admin approves the request.</CardDescription></CardHeader><CardContent><div className="space-y-3">{pending.length===0?<p className="text-sm text-muted-foreground">No pending requests.</p>:pending.map(r=><div key={r.uid||r.id} className="rounded-xl border p-4 flex items-center justify-between gap-4 flex-wrap"><div><p className="font-medium">{r.name}</p><p className="text-xs text-muted-foreground">{r.email||"—"} · {r.phone||"—"}</p><p className="text-xs text-muted-foreground mt-1">Requested {r.createdAt?new Date(r.createdAt).toLocaleString():"—"}</p></div><div className="flex gap-2"><Button size="sm" onClick={()=>review(r.id,"approved")}><Check className="size-4 mr-1"/>Approve</Button><Button size="sm" variant="outline" onClick={()=>review(r.id,"rejected")}><X className="size-4 mr-1"/>Reject</Button></div></div>)}</div></CardContent></Card>}
  {tab==="coins"&&<div className="space-y-4"><Card><CardHeader><CardTitle><Settings2 className="inline size-5 mr-2"/>Reward coin settings</CardTitle><CardDescription>These rules control earning and redemption. Customers never see their balance.</CardDescription></CardHeader><CardContent className="grid md:grid-cols-5 gap-4"><label className="text-sm flex items-center gap-2"><input type="checkbox" checked={settings.enabled!==false} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/> Coins enabled</label><Input type="number" min="0" step="0.01" value={settings.earnPer100} onChange={e=>setSettings({...settings,earnPer100:e.target.value})} placeholder="Coins per ৳100"/><Input type="number" min="0.01" step="0.01" value={settings.coinValue} onChange={e=>setSettings({...settings,coinValue:e.target.value})} placeholder="৳ value / coin"/><Input type="number" min="1" max="100" value={settings.maxRedeemPercent} onChange={e=>setSettings({...settings,maxRedeemPercent:e.target.value})} placeholder="Max redeem %"/><Button onClick={saveSettings} disabled={saving}><Save className="size-4 mr-2"/>Save rules</Button></CardContent></Card><Card><CardHeader><CardTitle>Product earning rules</CardTitle><CardDescription>Override the default earning rate or disable coins for any product.</CardDescription></CardHeader><CardContent><div className="space-y-2">{products.map(p=>{const r=ruleMap[p.id]||{disabled:false,earnPer100:settings.earnPer100};return <div key={p.id} className="grid md:grid-cols-[1fr_150px_120px] gap-3 items-center rounded-xl border p-3"><div><p className="font-medium">{p.name}</p><p className="text-xs text-muted-foreground">Code: {p.productCode||p.id} · Price ৳{Number(p.price||0).toLocaleString()}</p></div><Input type="number" min="0" step="0.01" value={r.earnPer100} onChange={e=>changeRate(p.id,e.target.value)} onBlur={()=>saveRule(p)}/><Button size="sm" variant={r.disabled?"destructive":"outline"} onClick={()=>toggleRule(p,r.disabled!==true)}>{r.disabled?"Coins off":"Coins on"}</Button></div>})}</div></CardContent></Card></div>}
  {tab==="announce"&&<Card><CardHeader><CardTitle><Mail className="inline size-5 mr-2"/>Member announcement</CardTitle><CardDescription>Send an in-app message and email to every active ArtCanvas member about offers, new products or important dates.</CardDescription></CardHeader><CardContent><Textarea rows={7} placeholder="Example: New ArtCanvas collection arrives on 25 September. Members get early access…" value={broadcast} onChange={e=>setBroadcast(e.target.value)}/><div className="flex justify-between items-center mt-3"><p className="text-xs text-muted-foreground">Recipients: {members.length} active members</p><Button onClick={sendBroadcast} disabled={saving||!broadcast.trim()}><Send className="size-4 mr-2"/>Send to all members</Button></div><p className="text-xs text-muted-foreground mt-4">Email delivery uses the backend Resend configuration. If the email provider is not configured, the request will report an error instead of silently claiming delivery.</p></CardContent></Card>}
 </div>
}
