"use client"
import {useEffect,useMemo,useState} from "react"
import {ShieldCheck,UserPlus,RefreshCw,Trash2,Save,Lock,Unlock,Search} from "lucide-react"
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card"
import {Input} from "@/components/ui/input"
import {Button} from "@/components/ui/button"
import {Badge} from "@/components/ui/badge"
import {Separator} from "@/components/ui/separator"
import {getAllAdmins,createAdmin,updateAdmin,deleteAdmin} from "@/lib/firebase/services/admin-admins"
import {useAdminAuth} from "@/contexts/admin-auth-context"
import {ALL_PERMISSIONS,PERMISSION_LABELS,ROLE_DEFAULTS,effectivePermissions,PermissionKey} from "@/lib/admin-permissions"

const emptyForm={name:"",email:"",role:"Moderator" as "Admin"|"Moderator"|"Seller"}

export default function AdminsPage(){
 const {admin:me,hasPermission}=useAdminAuth();
 const [admins,setAdmins]=useState<any[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[editing,setEditing]=useState<any>(null),[form,setForm]=useState(emptyForm),[customPermissions,setCustomPermissions]=useState<any>(ROLE_DEFAULTS.Moderator)
 const canManage=hasPermission("manageAdmins")
 const load=async()=>{setLoading(true);setError("");try{const r=await getAllAdmins(100);setAdmins(r.admins||[])}catch(e:any){setError(e.message||"Could not load admins.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const visible=useMemo(()=>admins.filter(a=>`${a.name} ${a.email} ${a.role}`.toLowerCase().includes(query.toLowerCase())),[admins,query])
 const openNew=()=>{setEditing({new:true});setForm(emptyForm);setCustomPermissions({...ROLE_DEFAULTS.Moderator})}
 const edit=(a:any)=>{setEditing(a);setForm({name:a.name||"",email:a.email||"",role:a.role||"Seller"});setCustomPermissions({...effectivePermissions(a)})}
 const save=async(e:any)=>{e.preventDefault();if(!canManage)return;setSaving(true);setError("");try{
   if(editing?.new){await createAdmin({name:form.name.trim(),email:form.email.trim().toLowerCase(),role:form.role,status:"active",permissions:customPermissions},me?.uid||me?.email||"admin")}
   else {await updateAdmin(editing.id,{name:form.name.trim(),role:form.role,permissions:customPermissions})}
   setEditing(null);await load()
 }catch(e:any){setError(e.message||"Could not save admin.")}finally{setSaving(false)}}
 const suspend=async(a:any)=>{if(!canManage||a.id===me?.uid)return;setSaving(true);try{await updateAdmin(a.id,{status:a.status==="suspended"?"active":"suspended"});await load()}catch(e:any){setError(e.message||"Could not update status")}finally{setSaving(false)}}
 const remove=async(a:any)=>{if(!canManage||a.id===me?.uid)return;if(!confirm(`Remove admin access for ${a.email}?`))return;setSaving(true);try{await deleteAdmin(a.id);await load()}catch(e:any){setError(e.message||"Could not remove admin")}finally{setSaving(false)}}
 if(!canManage)return <div className="px-4 lg:px-6"><Card><CardHeader><CardTitle>Admins & Roles</CardTitle><CardDescription>Your account does not have permission to manage administrators.</CardDescription></CardHeader></Card></div>
 return <div className="px-4 lg:px-6 space-y-6">
  <div className="flex items-start justify-between gap-4 flex-wrap"><div><p className="text-xs uppercase tracking-[.18em] text-primary">Administration</p><h1 className="text-3xl font-semibold tracking-tight mt-1">Admins & Roles</h1><p className="text-sm text-muted-foreground mt-2">Add workers, assign roles, and lock each admin to the access they need.</p></div><Button onClick={openNew}><UserPlus className="size-4 mr-2"/> Add admin</Button></div>
  {error&&<div className="rounded-lg border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}
  {editing&&<Card><CardHeader><CardTitle>{editing.new?"Add administrator":"Edit administrator"}</CardTitle><CardDescription>{editing.new?"Use the worker's Firebase account email. If the account already exists, their admin access will be linked on next sign-in.":"Change role or profile details without changing their storefront account."}</CardDescription></CardHeader><CardContent><form onSubmit={save} className="space-y-5"><div className="grid md:grid-cols-2 gap-4"><label className="space-y-2 text-sm"><span className="font-medium">Full name</span><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="space-y-2 text-sm"><span className="font-medium">Email</span><Input required type="email" disabled={!editing.new} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div><label className="space-y-2 text-sm block max-w-sm"><span className="font-medium">Role</span><select className="w-full h-10 rounded-md border bg-background px-3 text-sm" value={form.role} onChange={e=>{const role=e.target.value as "Admin"|"Moderator"|"Seller";setForm({...form,role});setCustomPermissions({...ROLE_DEFAULTS[role]})}}>{["Admin","Moderator","Seller"].map(r=><option key={r}>{r}</option>)}</select></label><div className="rounded-xl border p-4"><p className="font-medium text-sm">Access control</p><p className="text-xs text-muted-foreground mt-1">Choose exactly what this administrator can access. The Admin role can be given full access when you want someone to be an owner-level admin.</p><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-4">{ALL_PERMISSIONS.map(p=><label key={p} className="flex items-center gap-2 rounded-lg border px-3 py-2.5 text-xs cursor-pointer"><input type="checkbox" disabled={form.role==="Admin"} checked={form.role==="Admin"?true:!!customPermissions[p]} onChange={e=>setCustomPermissions((v:any)=>({...v,[p]:e.target.checked}))}/><span>{PERMISSION_LABELS[p]}</span></label>)}</div></div><div className="flex gap-2"><Button disabled={saving} type="submit"><Save className="size-4 mr-2"/>{saving?"Saving…":"Save admin"}</Button><Button type="button" variant="outline" onClick={()=>setEditing(null)}>Cancel</Button></div></form></CardContent></Card>}
  <Card><CardHeader className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><CardTitle>Team</CardTitle><CardDescription>{admins.length} administrator account{admins.length!==1?"s":""}</CardDescription></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search admins…" className="pl-9 w-64"/></div><Button variant="outline" size="icon" onClick={load} title="Refresh"><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/></Button></div></CardHeader><CardContent><div className="space-y-2">{loading?<p className="text-sm text-muted-foreground py-8 text-center">Loading administrators…</p>:visible.length===0?<p className="text-sm text-muted-foreground py-8 text-center">No matching administrators.</p>:visible.map(a=>{const perms=effectivePermissions(a);return <div key={a.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2 flex-wrap"><p className="font-medium truncate">{a.name||"Unnamed admin"}</p><Badge variant="outline">{a.role}</Badge><Badge variant={a.status==="active"?"secondary":"destructive"}>{a.status}</Badge>{a.id===me?.uid&&<Badge>YOU</Badge>}</div><p className="text-sm text-muted-foreground mt-1">{a.email}</p><p className="text-xs text-muted-foreground mt-2">{Object.values(perms).filter(Boolean).length} of {ALL_PERMISSIONS.length} access areas enabled</p></div><div className="flex gap-2 shrink-0"><Button variant="outline" size="sm" onClick={()=>edit(a)}>Edit</Button>{a.id!==me?.uid&&<><Button variant="outline" size="icon" onClick={()=>suspend(a)} title={a.status==="suspended"?"Activate":"Suspend"}>{a.status==="suspended"?<Unlock className="size-4"/>:<Lock className="size-4"/>}</Button><Button variant="outline" size="icon" className="text-destructive" onClick={()=>remove(a)} title="Remove"><Trash2 className="size-4"/></Button></>}</div></div><Separator className="my-4"/><div className="flex flex-wrap gap-2">{ALL_PERMISSIONS.filter(p=>perms[p]).map(p=><span key={p} className="text-[11px] rounded-full bg-muted px-2.5 py-1">{PERMISSION_LABELS[p]}</span>)}</div></div>})}</div></CardContent></Card>
 </div>
}
